import numpy as np

def generate_fcc_cluster(element, lattice_constant, size):
    """
    English: Generates a Face-Centered Cubic (FCC) lattice for a metal nanoparticle.
    Russian: Генерирует гранецентрированную кубическую решетку (ГЦК) для наночастицы металла.
    """
    atoms = []
    r = size  # Radius in lattice units / Радиус в единицах решетки
    
    # Grid search for atoms inside the sphere
    # Перебор точек в пространстве для поиска атомов внутри сферы
    for x in range(-r, r+1):
        for y in range(-r, r+1):
            for z in range(-r, r+1):
                # Check FCC condition (x, y, z must have same parity)
                # Проверка условия ГЦК (сумма координат должна быть четной для стандартной ячейки)
                if (x + y + z) % 2 == 0:
                    # Calculate distance from center / Считаем расстояние от центра
                    dist = np.sqrt(x**2 + y**2 + z**2)
                    if dist <= r:
                        # Scale coordinates by lattice constant
                        # Масштабируем координаты на постоянную решетки (для Серебра ~4.09 A)
                        # We use 0.5 factor because integer steps correspond to half-cells
                        px = x * lattice_constant / 2.0
                        py = y * lattice_constant / 2.0
                        pz = z * lattice_constant / 2.0
                        atoms.append((element, px, py, pz))
    
    return atoms

def save_xyz(filename, atoms):
    with open(filename, "w") as f:
        f.write(f"{len(atoms)}\n")
        f.write("Generated by HeLa_Project_2026\n")
        for atom in atoms:
            f.write(f"{atom[0]} {atom[1]:.3f} {atom[2]:.3f} {atom[3]:.3f}\n")

if __name__ == "__main__":
    # Silver (Ag) parameters:
    # Lattice constant: 4.09 Angstroms
    # Size: ~2-3 nm radius
    print("🚀 Starting Silver (Ag) Nanoparticle Generation...")
    
    ag_atoms = generate_fcc_cluster("Ag", 4.09, 6)
    
    output_file = "../data/nanomaterials/Ag_2026_model.xyz"
    
    # Ensure folder exists / Создаем папку если нет
    import os
    os.makedirs("../data/nanomaterials", exist_ok=True)
    
    save_xyz(output_file, ag_atoms)
    
    print(f"✅ Created Silver cluster with {len(ag_atoms)} atoms.")
    print(f"📁 File saved to: {output_file}")